name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint code using SwiftLint
      run: swiftlint lint --reporter github-actions-logging
